[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32@6.8.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.psram = enabled
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 115200
upload_flags = --no-stub
build_src_filter =
    +<*>
    -<diag/>
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_LOOP_STACK_SIZE=32768
    -DCORE_DEBUG_LEVEL=4
    -DLOG_LOCAL_LEVEL=ESP_LOG_INFO
    -DJPV2G_ENABLE_CBV2G_CODEC=1
    -DJPV2G_LOG_LEVEL=JPV2G_LOG_INFO
extra_scripts = pre:extra_script.py
lib_deps =
    fastled/FastLED@^3.7.8
    hideakitai/PCA95x5@^0.1.3
    miguelbalboa/MFRC522@^1.4.10

[env:controller-plc1]
extends = env:esp32-s3-devkitc-1
build_flags =
    ${env:esp32-s3-devkitc-1.build_flags}
    -DCBPLC_ENABLE_STATUS_LEDS=0
    -DCBPLC_DEFAULT_MODE=1
    -DCBPLC_DEFAULT_SLAC_REQUIRES_CONTROLLER_START=1
    -DCBPLC_DEFAULT_PLC_ID=1
    -DCBPLC_DEFAULT_CONNECTOR_ID=1
    -DCBPLC_DEFAULT_CONTROLLER_ID=7
    -DCBPLC_DEFAULT_LOCAL_MODULE_ADDRESS=1
    -DCBPLC_DEFAULT_CAN_NODE_ID=10

[env:standalone-plc1]
extends = env:esp32-s3-devkitc-1
build_flags =
    ${env:esp32-s3-devkitc-1.build_flags}
    -DCBPLC_DEFAULT_MODE=0
    -DCBPLC_DEFAULT_SLAC_REQUIRES_CONTROLLER_START=0
    -DCBPLC_DEFAULT_PLC_ID=1
    -DCBPLC_DEFAULT_CONNECTOR_ID=1
    -DCBPLC_DEFAULT_CONTROLLER_ID=1
    -DCBPLC_DEFAULT_LOCAL_MODULE_ADDRESS=1
    -DCBPLC_DEFAULT_CAN_NODE_ID=10

[env:controller-plc2]
extends = env:esp32-s3-devkitc-1
build_flags =
    ${env:esp32-s3-devkitc-1.build_flags}
    -DCBPLC_ENABLE_STATUS_LEDS=0
    -DCBPLC_DEFAULT_MODE=1
    -DCBPLC_DEFAULT_SLAC_REQUIRES_CONTROLLER_START=1
    -DCBPLC_DEFAULT_PLC_ID=2
    -DCBPLC_DEFAULT_CONNECTOR_ID=2
    -DCBPLC_DEFAULT_CONTROLLER_ID=7
    -DCBPLC_DEFAULT_LOCAL_MODULE_ADDRESS=3
    -DCBPLC_DEFAULT_CAN_NODE_ID=11

[env:standalone-plc2]
extends = env:esp32-s3-devkitc-1
build_flags =
    ${env:esp32-s3-devkitc-1.build_flags}
    -DCBPLC_DEFAULT_MODE=0
    -DCBPLC_DEFAULT_SLAC_REQUIRES_CONTROLLER_START=0
    -DCBPLC_DEFAULT_PLC_ID=2
    -DCBPLC_DEFAULT_CONNECTOR_ID=2
    -DCBPLC_DEFAULT_CONTROLLER_ID=1
    -DCBPLC_DEFAULT_LOCAL_MODULE_ADDRESS=3
    -DCBPLC_DEFAULT_CAN_NODE_ID=11

[env:hw-diag]
extends = env:esp32-s3-devkitc-1
build_src_filter =
    -<*>
    +<diag/hw_diag_main.cpp>
